version: '3.3'
services:
    linuxserver:
        container_name: heimdall
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '~/heimdall/appdata/config:/config'
        restart: unless-stopped
        image: 'lscr.io/linuxserver/heimdall:latest'
        platform: linux/arm64/v8
